idf_component_register(
    SRCS
        "main.cpp"
        "MSM_CAN/MSM_CAN.cpp"
        "tasks/can_task/can_task.cpp"
        "tasks/shifter_task/shifter_task.cpp"
        "tasks/system_task/system_task.cpp"
    PRIV_REQUIRES
        freertos
        log
        spi_flash
        esp_driver_twai
        esp_driver_gpio
        esp_timer
    INCLUDE_DIRS
        "."
        "MSM_CAN"
        "tasks/can_task"
        "tasks/shifter_task"
        "tasks/system_task"
)
