idf_component_register(
    SRCS
        "main.cpp"
        "encoder/AMT20.cpp"
        "tasks/gear_safety_task/gear_safety_task.cpp"
        "tasks/gear_safety_task/shift_inputs.cpp"
    PRIV_REQUIRES
        freertos
        log
        spi_flash
        esp_driver_gpio
        esp_driver_ledc
        esp_driver_spi
        esp_timer
    INCLUDE_DIRS
        "."
        "encoder"
        "esc"
        "tasks/gear_safety_task"
)
