idf_component_register(
    SRCS
        "main.cpp"
        "esc/ESC.cpp"
        "interrupts/shift_inputs.cpp"
        "tasks/shifter_task/shifter_task.cpp"
    PRIV_REQUIRES
        freertos
        log
        spi_flash
        esp_driver_gpio
        esp_driver_ledc
    INCLUDE_DIRS
        "."
        "esc"
        "interrupts"
        "tasks/shifter_task"
)
